# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-9
  region: ap-south-1

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
